In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.view()

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [30]:
random_array

array([[2, 9, 0, 0, 9],
       [0, 8, 4, 0, 6],
       [9, 5, 3, 1, 1]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [34]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.8328105 , 0.62100049, 0.54428346],
       [0.06770778, 0.67608016, 0.38035529],
       [0.02345606, 0.06838893, 0.70308968],
       [0.69192945, 0.07114974, 0.3002376 ],
       [0.02408712, 0.71108431, 0.9910589 ]])

In [35]:
random_array2.shape

(5, 3)

In [40]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.44539362, 0.39252249, 0.79868663],
       [0.6853348 , 0.79881193, 0.87376603],
       [0.48691785, 0.72082317, 0.81332267],
       [0.80005967, 0.72298047, 0.25381388],
       [0.92238851, 0.83800743, 0.19636742]])

In [53]:
# Pseudo-random numbers
np.random.seed(seed=42)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [60]:
np.random.seed(7)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [66]:
random_array5 = np.random.random((5, 3))
random_array5

array([[0.48582523, 0.13687612, 0.34353653],
       [0.32442617, 0.3004189 , 0.1655014 ],
       [0.41490177, 0.44812066, 0.77490038],
       [0.7963907 , 0.52239013, 0.4606303 ],
       [0.7782136 , 0.88728895, 0.67491877]])

In [61]:
random_array4.shape

(5, 3)