In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.view()

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [30]:
random_array

array([[2, 9, 0, 0, 9],
       [0, 8, 4, 0, 6],
       [9, 5, 3, 1, 1]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [34]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.8328105 , 0.62100049, 0.54428346],
       [0.06770778, 0.67608016, 0.38035529],
       [0.02345606, 0.06838893, 0.70308968],
       [0.69192945, 0.07114974, 0.3002376 ],
       [0.02408712, 0.71108431, 0.9910589 ]])

In [35]:
random_array2.shape

(5, 3)

In [36]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.42963735, 0.19484196, 0.00820403],
       [0.19426576, 0.81377145, 0.58228669],
       [0.51983123, 0.0034439 , 0.30432293],
       [0.38314612, 0.64321175, 0.47103584],
       [0.67926071, 0.75132961, 0.35781215]])

In [37]:
# Pseudo-random numbers
np.random.seed()