In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.view()

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [25]:
random_array

array([[8, 6, 2, 0, 1],
       [2, 9, 0, 2, 0],
       [1, 1, 7, 5, 4]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array2 = np.random.random((5, 3))
random_array2

array([[0.43955519, 0.66114636, 0.94960602],
       [0.85483912, 0.55922288, 0.51757602],
       [0.86498318, 0.28673196, 0.44068125],
       [0.74461393, 0.88836224, 0.57357867],
       [0.4958766 , 0.06465879, 0.82723265]])

In [29]:
random_array2.shape

(5, 3)

In [30]:
random_array3 = np.random.rand(5, 3)
random_array3

array([[0.63748834, 0.55116121, 0.86830675],
       [0.95231595, 0.99659335, 0.67955624],
       [0.88517692, 0.20190139, 0.93086215],
       [0.77094031, 0.60629877, 0.89998855],
       [0.19313867, 0.64167274, 0.01279503]])

In [31]:
# Pseudo-random numbers
np.random.seed(seed=42)
random_array4 = np.random.randint(10, size=(5, 3))
random_array4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [32]:
np.random.seed(7)
random_array5 = np.random.random((5, 3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [33]:
random_array5 = np.random.random((5, 3))
random_array5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [34]:
random_array4.shape

(5, 3)

## Viewing arrays and matrices

In [35]:
np.unique(random_array4)

array([2, 3, 4, 5, 6, 7, 9])

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a1[0]

1

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
a2[1]

array([4. , 5. , 6.5])

In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [46]:
a3[:2, :2 , :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [48]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

### Get the first 4 numbers of the inner most arrays

In [49]:
a4[:, :, :, :4]

array([[[[6, 7, 7, 9],
         [0, 7, 7, 7],
         [5, 4, 3, 1],
         [1, 3, 4, 3]],

        [[9, 5, 9, 1],
         [3, 2, 2, 5],
         [3, 0, 9, 9],
         [4, 5, 3, 0]],

        [[8, 6, 7, 2],
         [3, 8, 6, 6],
         [6, 5, 7, 1],
         [4, 4, 9, 9]]],


       [[[6, 2, 6, 8],
         [4, 1, 6, 1],
         [1, 6, 9, 8],
         [5, 9, 7, 5]],

        [[9, 6, 8, 1],
         [5, 8, 3, 7],
         [9, 4, 7, 5],
         [6, 2, 0, 5]],

        [[0, 5, 7, 1],
         [4, 9, 0, 2],
         [7, 6, 2, 9],
         [5, 1, 0, 0]]]])

## Manipulating and Comparing arrays

### Arithmetic

In [50]:
a1

array([1, 2, 3])

In [51]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [52]:
a1 + ones

array([2., 3., 4.])

In [53]:
a1 - ones

array([0., 1., 2.])

In [54]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [55]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [56]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [57]:
# Reshaping numpy arrays
a4 = a3.reshape(3, 2, 3)

In [58]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [59]:
a2 * a4

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [60]:
a1 / ones

array([1., 2., 3.])

In [61]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [62]:
# Floor division removes decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [63]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [64]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [65]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [66]:
np.add(a1, ones)

array([2., 3., 4.])

In [67]:
a1

array([1, 2, 3])

In [68]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [69]:
a1 / 2

array([0.5, 1. , 1.5])

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = Performing the same operation on a number of things

In [72]:
listy_list = [1, 2, 3]

In [73]:
type(listy_list)

list

In [74]:
sum(listy_list)

6

In [75]:
type(a1)

numpy.ndarray

In [76]:
sum(a1)

6

In [77]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [78]:
# Creating a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [80]:
massive_array[:10]

array([0.62342345, 0.62955693, 0.9099729 , 0.96251949, 0.5850998 ,
       0.16489774, 0.39159332, 0.94455493, 0.34339118, 0.70507037])

In [81]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

13.7 ms ± 256 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
38.3 µs ± 564 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [82]:
13700/38.3

357.7023498694517

In [83]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [84]:
np.mean(a2)

3.6333333333333333

In [85]:
np.max(a2)

6.5

In [86]:
np.min(a2)

1.0

In [87]:
# Standard deviation = measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [88]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [89]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422